### ISSUE TITLE
Mobile Menu First Link not active V1 and V2

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/supreme-directory#12]
In mobile the parent menu item is not an active link.
This was an issue with V1 that we fixed at one point but is back 
https://ppldb.com/v2/
![image](https://user-images.githubusercontent.com/114659/48967422-6de16180-efe0-11e8-9aa7-0edcf3534c53.png)

same issue in V1
https://ppldb.com/123/ (try the checkout link)
![image](https://user-images.githubusercontent.com/114659/48967444-d597ac80-efe0-11e8-99ab-762e5e506447.png)

**Comment by Stiofan** [comment]
related, it can be changed functionality wise with CSS https://wpgeodirectory.com/support/topic/supreme-directory-responsive-issue/page/2/#post-401325

**Comment by kprajapatii** [comment]
Fixed
See https://github.com/AyeCode/directory-starter/pull/4/commits/5234236de8335ffc04f87b59974abbf4e2314bd9
