### ISSUE TITLE
ER: Options for GD Map for Archive template

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/supreme-directory#27]
Provide some option, either a snippet or settings panel, so users can adjust the properties of the GD Map element used in the archive template sidebar.

https://wpgeodirectory.com/support/topic/marker-cluster-plugins-do-not-work/

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/supreme-directory/pull/28/commits/5d38f0bb98be086dec353b254175abcb90f50e31
