### ISSUE TITLE
ER: Remove Show Map Button on Mobile View when CPT has no physical location

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/supreme-directory#4]
Currently map is being hidden on desktop and mobile if CPT has no address, but, there is still the show map button on mobile view

https://ppldb.com/v2/ishop/

![screenshot 2018-09-28 at 12 13 21 pm](https://user-images.githubusercontent.com/114659/46202833-23ad6e00-c318-11e8-9221-f7f9ce9a292a.png)

![screenshot 2018-09-28 at 12 18 45 pm](https://user-images.githubusercontent.com/114659/46203005-b1895900-c318-11e8-98ec-165a5eb670b2.png)

Reported here:
https://wpgeodirectory.com/support/topic/remove-show-map-for-no-address/#post-448039
(This was reported on V1, but the CSS fixes are hard for members to maintain. They would appreciate a theme fix to support CPTs with no physical location)

**Comment by Stiofan** [comment]
Fixed in v2
