### ISSUE TITLE
Support for Bootstrap V5 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/supreme-directory#79]
The style gets distorted when I use Bootstrap v5 
https://secure.helpscout.net/conversation/2643354810/57879?folderId=3812058

<img width="1562" alt="Screenshot 2024-07-04 at 5 16 28 PM" src="https://github.com/AyeCode/supreme-directory/assets/24760592/89b13607-fa16-4518-abcc-daf071cce30c">

**Comment by Stiofan** [comment]
The old themes do not support v5. we do not intend to make them compatible, they will soon be retired.
